logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    org.morshed: DEBUG

spring:
  redis:
    host: localhost
    port: 6379
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: true # we use Webpack dev server + BrowserSync for livereload

application:
  name: server1

