# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.5.3
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kvloadbalancer:
    image: kvloadbalancer:latest
    ports:
      - 8761:8761
    environment:
      KVLOAD_BALANCER_SLEEP: 0s
  keyvaluestore1-redis:
    image: redis:6.2.1
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 6379:6379
  keyvaluestore1:
    image: keyvaluestore:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
    - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_NAME: server1
      SERVER_PORT: 8080
      REDIS_HOST: keyvaluestore1-redis
      REDIS_PORT: 6379
      EUREKA_URL: host.docker.internal:8761/eureka
      INSTANCE_ID: keyvaluestore1
      KAFKA_HOST: kafka:9092
      KEY_VALUE_STORE_SLEEP: 10s
      GROUP_ID: GROUP_ID1
  keyvaluestore2-redis:
    image: redis:6.2.1
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 6380:6379
  keyvaluestore2:
    image: keyvaluestore:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8081:8081
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8081
      SERVER_NAME: server2
      REDIS_HOST: keyvaluestore2-redis
      REDIS_PORT: 6379
      EUREKA_URL: host.docker.internal:8761/eureka
      INSTANCE_ID: keyvaluestore2
      KAFKA_HOST: kafka:9092
      KEY_VALUE_STORE_SLEEP: 10s
      GROUP_ID: GROUP_ID2
  keyvaluestore3-redis:
    image: redis:6.2.1
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 6381:6379
  keyvaluestore3:
    image: keyvaluestore:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8082:8082
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8082
      SERVER_NAME: server3
      REDIS_HOST: keyvaluestore3-redis
      REDIS_PORT: 6379
      EUREKA_URL: host.docker.internal:8761/eureka
      INSTANCE_ID: keyvaluestore3
      KAFKA_HOST: kafka:9092
      KEY_VALUE_STORE_SLEEP: 10s
      GROUP_ID: GROUP_ID3

#  keyvaluestore4-redis:
#    image: redis:6.2.1
#    # If you want to expose these ports outside your dev PC,
#    # remove the "127.0.0.1:" prefix
#    ports:
#      - 6382:6379
#  keyvaluestore4:
#    image: keyvaluestore:latest
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    ports:
#      - 8083:8083
#    environment:
#      SPRING_PROFILES_ACTIVE: prod
#      SERVER_PORT: 8083
#      SERVER_NAME: server4
#      REDIS_HOST: keyvaluestore4-redis
#      REDIS_PORT: 6379
#      EUREKA_URL: host.docker.internal:8761/eureka
#      INSTANCE_ID: keyvaluestore4
#      KAFKA_HOST: kafka:9092
#      KEY_VALUE_STORE_SLEEP: 10s
#      GROUP_ID: GROUP_ID4
#
#  keyvaluestore5-redis:
#    image: redis:6.2.1
#    # If you want to expose these ports outside your dev PC,
#    # remove the "127.0.0.1:" prefix
#    ports:
#      - 6383:6379
#  keyvaluestore5:
#    image: keyvaluestore:latest
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    ports:
#      - 8084:8084
#    environment:
#      SPRING_PROFILES_ACTIVE: prod
#      SERVER_PORT: 8084
#      SERVER_NAME: server5
#      REDIS_HOST: keyvaluestore5-redis
#      REDIS_PORT: 6379
#      EUREKA_URL: host.docker.internal:8761/eureka
#      INSTANCE_ID: keyvaluestore5
#      KAFKA_HOST: kafka:9092
#      KEY_VALUE_STORE_SLEEP: 10s
#      GROUP_ID: GROUP_ID5
